//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansveSalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dans()
        {
            this.ogrenciders = new HashSet<ogrenciders>();
            this.ogretmendans = new HashSet<ogretmendans>();
        }
    
        public int dansid { get; set; }
        public string dansadi { get; set; }
        public string dansmemleket { get; set; }
        public Nullable<decimal> dansfiyat { get; set; }
        public Nullable<System.DateTime> danssure { get; set; }
        public int danskodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciders> ogrenciders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogretmendans> ogretmendans { get; set; }
    }
}
