//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansveSalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogretmendans
    {
        public int ogrdesid { get; set; }
        public int ogrid { get; set; }
        public int dansid { get; set; }
    
        public virtual dans dans { get; set; }
        public virtual ogretmen ogretmen { get; set; }
    }
}
