//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansveSalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenci()
        {
            this.ogrenciders = new HashSet<ogrenciders>();
        }
    
        public int ono { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<int> yası { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<int> boy { get; set; }
        public Nullable<int> kilo { get; set; }
        public string eposta { get; set; }
        public string psw { get; set; }
        public string telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciders> ogrenciders { get; set; }
    }
}
