//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansveSalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciders
    {
        public int ono { get; set; }
        public int dansid { get; set; }
        public int ogdersid { get; set; }
    
        public virtual dans dans { get; set; }
        public virtual ogrenci ogrenci { get; set; }
    }
}
